installCRDs: true

serviceAccount:
  create: true
  name: external-secrets-sa
  annotations:
    azure.workload.identity/client-id: "e66ac6af-1d7d-445d-a8f7-334749105a47"

# Pin all pods to tools pool
nodeSelector: {}

tolerations: []

webhook:
  nodeSelector: {}
  tolerations: []

certController:
  nodeSelector: {}
  tolerations: []
