provider:
  name: azure

serviceAccount:
  create: true
  name: external-dns-sa
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "52265180-fb17-41ab-92a0-8eff8bf9e0d9"

podLabels:
  azure.workload.identity/use: "true"

extraVolumes:
  - name: azure-config-file
    configMap:
      name: external-dns-azure-config

extraVolumeMounts:
  - name: azure-config-file
    mountPath: /etc/kubernetes
    readOnly: true

extraArgs:
  - --azure-config-file=/etc/kubernetes/azure.json

# Ensure pods run on the tools pool
nodeSelector: {}

tolerations: []
