provider: azure

azure:
  # The Azure Tenant ID
  tenantId: "5b7591f7-41a6-408a-90be-2e5e1e9d386b"
  # The Azure Subscription ID
  subscriptionId: "16ae35b8-3311-486c-b92e-edfd46b1e826"
  # The resource group where the public/private DNS zones are located in prod
  resourceGroup: "voyager-prod-rg"
  # Use Workload Identity for authentication instead of a client secret file
  useWorkloadIdentityExtension: true

serviceAccount:
  create: true
  name: external-dns-sa
  annotations:
    # REPLACE with the client ID of the External DNS User Assigned Identity (outputted as external_dns_identity_client_id by Terraform in prod)
    azure.workload.identity/client-id: "external-dns-identity-client-id-placeholder-prod"

# Ensure pods run on the tools pool
nodeSelector:
  role: tools

tolerations:
  - key: "role"
    operator: "Equal"
    value: "tools"
    effect: "NoSchedule"
