apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/emyeugdcd/voyager.git'
    path: charts/frontend
    helm:
      valueFiles:
        - values-test.yaml # In production, this will be values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
