apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    app: {{ include "backend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.fullname" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
            - name: DB_HOST
              value: "{{ .Values.database.host }}"
            - name: DB_NAME
              value: "{{ .Values.database.name }}"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-db-credentials
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-db-credentials
                  key: db-password
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
