apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: backend-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: pg-admin-user
    - secretKey: db-password
      remoteRef:
        key: pg-admin-password
