replicaCount: 1

image:
  repository: "voyageracrshared.azurecr.io/backend"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "backend.test-public.voyager-cloud.com"
  hosts:
    - host: backend.test-public.voyager-cloud.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: backend-tls
      hosts:
        - backend.test-public.voyager-cloud.com

database:
  # The FQDN of the PostgreSQL server (outputted as db_fqdn by Terraform)
  host: "voyager-test-db.postgres.database.azure.com"
  name: "sampleapp"

# Pin backend pods to main pool
nodeSelector:
  role: main

tolerations: []
affinity: {}
