global:
  nodeSelector:
    role: main

server:
  nodeSelector:
    role: main

controller:
  nodeSelector:
    role: main

repoServer:
  nodeSelector:
    role: main

redis:
  nodeSelector:
    role: main

applicationSet:
  nodeSelector:
    role: main

notifications:
  nodeSelector:
    role: main